### ISSUE TITLE
Error in event handler for vuex:init with args

### ISSUE THREAD

**Issue by matthias-glatthorn** [ManuelSch/vuex-rxjs#28]
Hi there,

I implemented vuex-rxjs store exactly like you described in the section "the simple way". But I'm getting this error in Chrome Devtools:

``` Error in event handler for vuex:init with args ```

I am also getting a TypeError:

```
VM11:1 TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.<anonymous> (<anonymous>:1:2660)
    at Object.n (<anonymous>:1:1747)
    at Object.emit (<anonymous>:1:2053)
    at Object.initialize (devtools.js?fd31:16:1)
    at new Store (store.js?10ea:18:1)
    at new SimpleStore (store.ts?7fab:13:1)
    at eval (store.ts?7fab:35:1)
    at ./src/store.ts (app.js:1304:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
```

Do have suggestions on how I could fix these Errors?

**Comment by zkk1234567** [comment]
Have you solved it yet?
